name: frontend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: aws s3 sync . s3://udemy-github-actions-s3-yoshimatsu --exact-timestamps --region ap-northeast-1


# workflow
# on: トリガー
# job: 実行するもの 複数のstepからなる usesやactionsを使う

# アーティファクト：ビルド結果の成果物など